repos:
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.15.6
  #   hooks:
  #     - id: ruff-check
  #       args: [ --fix ]
  #     - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      # - id: check-added-large-files
      - id: check-symlinks
      - id: destroyed-symlinks
      # - id: double-quote-string-fixer
  - repo: local
    hooks:
      # - id: ruff-check
      #   name: ruff check
      #   entry: uv run ruff check .
      #   language: system
      - id: ruff-check-fix
        name: ruff check-fix
        entry: uv run ruff check --fix
        language: system
        types_or: [python, jupyter]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, jupyter]
      # - id: ty
      #   name: ty check
      #   entry: uv run ty check .
      #   language: system
      #   pass_filenames: false
      - id: tex-fmt
        name: tex-fmt
        language: system
        entry: tex-fmt
        args: [--fail-on-change]
        files: \.(tex|bib|cls|sty)$
        stages: [pre-commit, pre-merge-commit, pre-push, manual]
